apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      labels:
        app: quotes
    spec:
      containers:
      - name: quotes
        image: yourdockerhubusername/daily-quotes-app:latest
        ports:
        - containerPort: 3000
